for number in "$@"; do
    case $number in
        0)
            echo "Running simulation set 0..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results0/lasso_b1.pkl" --b_function "b1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results0/tprior_b1.pkl" --b_function "b1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results0/gig01_01_-1_b1.pkl" --b_function "b1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results0/gig01_05_-3_b1.pkl" --b_function "b1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        1)
            echo "Running simulation set 1..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results1/lasso_b2.pkl" --b_function "b2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results1/tprior_b2.pkl" --b_function "b2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results1/gig01_01_-1_b2.pkl" --b_function "b2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results1/gig01_05_-3_b2.pkl" --b_function "b2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        2)
            echo "Running simulation set 2..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results2/lasso_b_gamma1.pkl" --b_function "b_gamma1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results2/tprior_b_gamma1.pkl" --b_function "b_gamma1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results2/gig01_01_-1_b_gamma1.pkl" --b_function "b_gamma1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results2/gig01_05_-3_b_gamma1.pkl" --b_function "b_gamma1" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        3)
            echo "Running simulation set 3..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results3/lasso_b_gamma2.pkl" --b_function "b_gamma2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results3/tprior_b_gamma2.pkl" --b_function "b_gamma2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results3/gig01_01_-1_b_gamma2.pkl" --b_function "b_gamma2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results3/gig01_05_-3_b_gamma2.pkl" --b_function "b_gamma2" --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        4)
            echo "Running simulation set 4..."
            # similar things, but using beta distribution instead of truncated normal for pi
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results4/lasso_b1_pibeta.pkl" --b_function "b1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results4/tprior_b1_pibeta.pkl" --b_function "b1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results4/gig01_01_-1_b1_pibeta.pkl" --b_function "b1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results4/gig01_05_-3_b1_pibeta.pkl" --b_function "b1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        5)
            echo "Running simulation set 5..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results5/lasso_b2_pibeta.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results5/tprior_b2_pibeta.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results5/gig01_01_-1_b2_pibeta.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results5/gig01_05_-3_b2_pibeta.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        6)
            echo "Running simulation set 6..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results6/lasso_b_gamma1_pibeta.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results6/tprior_b_gamma1_pibeta.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results6/gig01_01_-1_b_gamma1_pibeta.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results6/gig01_05_-3_b_gamma1_pibeta.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        7)
            echo "Running simulation set 7..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results7/lasso_b_gamma2_pibeta.pkl" --b_function "b_gamma2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results7/tprior_b_gamma2_pibeta.pkl" --b_function "b_gamma2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results7/gig01_01_-1_b_gamma2_pibeta.pkl" --b_function "b_gamma2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results7/gig01_05_-3_b_gamma2_pibeta.pkl" --b_function "b_gamma2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -50 50 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        8)
            echo "Running simulation set 8..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results8/lasso_b2_smally.pkl" --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results8/tprior_b2_smally.pkl" --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results8/gig01_01_-1_b2_smally.pkl" --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results8/gig01_05_-3_b2_smally.pkl" --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        9)
            echo "Running simulation set 9..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results9/lasso_b_gamma1_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results9/tprior_b_gamma1_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results9/gig01_01_-1_b_gamma1_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results9/gig01_05_-3_b_gamma1_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        10)
            echo "Running simulation set 10..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results10/lasso_b2_pibeta_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results10/tprior_b2_pibeta_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results10/gig01_01_-1_b2_pibeta_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results10/gig01_05_-3_b2_pibeta_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        11)
            echo "Running simulation set 11..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results11/lasso_b_gamma1_pibeta_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results11/tprior_b_gamma1_pibeta_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results11/gig01_01_-1_b_gamma1_pibeta_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results11/gig01_05_-3_b_gamma1_pibeta_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        12)
            echo "Running simulation set 12..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results12/lasso_b2_10trunc_smally.pkl" --b_function "b2" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results12/tprior_b2_10trunc_smally.pkl" --b_function "b2" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results12/gig01_01_-1_b2_10trunc_smally.pkl" --b_function "b2" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results12/gig01_05_-3_b2_10trunc_smally.pkl" --b_function "b2" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        13)
            echo "Running simulation set 13..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results13/lasso_b_gamma1_10trunc_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results13/tprior_b_gamma1_10trunc_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results13/gig01_01_-1_b_gamma1_10trunc_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results13/gig01_05_-3_b_gamma1_10trunc_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --a_trunc -10 --b_trunc 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        14)
            echo "Running simulation set 14..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results14/lasso_b2_pibeta_a6b1_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results14/tprior_b2_pibeta_a6b1_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results14/gig01_01_-1_b2_pibeta_a6b1_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results14/gig01_05_-3_b2_pibeta_a6b1_smally.pkl" --b_function "b2" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        15)
            echo "Running simulation set 15..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results15/lasso_b_gamma1_pibeta_a6b1_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results15/tprior_b_gamma1_pibeta_a6b1_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results15/gig01_01_-1_b_gamma1_pibeta_a6b1_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results15/gig01_05_-3_b_gamma1_pibeta_a6b1_smally.pkl" --b_function "b_gamma1" --pi beta --beta_distribution_a 6.5 --beta_distribution_b 1.5 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 250 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        16)
            echo "Running simulation set 16..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results16/lasso_b2_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results16/tprior_b2_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results16/gig01_01_-1_b2_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results16/gig01_05_-3_b2_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        17)
            echo "Running simulation set 17..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results17/lasso_b_gamma1_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results17/tprior_b_gamma1_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results17/gig01_01_-1_b_gamma1_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results17/gig01_05_-3_b_gamma1_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        18)
            echo "Running simulation set 18..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results18/lasso_b2_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results18/tprior_b2_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results18/gig01_01_-1_b2_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results18/gig01_05_-3_b2_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b2" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        19)
            echo "Running simulation set 19..."
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results19/lasso_b_gamma1_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 2 --local_gig_b 0 --local_gig_p 1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results19/tprior_b_gamma1_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0 --local_gig_b 2 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results19/gig01_01_-1_b_gamma1_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.1 --local_gig_p -1 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results19/gig01_05_-3_b_gamma1_pibeta_smally_multiexp.pkl" --kernel_name 'mult_exp' --b_function "b_gamma1" --pi beta --beta_distribution_a 3 --beta_distribution_b 2 --y_domain -10 10 --gibbs_iters 25 --t_end 100 --start_val 0.5 --chunk_size 300 --matrix_calc "chunked" --local_gig_a 0.1 --local_gig_b 0.5 --local_gig_p -3 --global_gig_a 0 --global_gig_b 0 --global_gig_p 0
            ;;
        20) # running long t_end and avoiding running the gibbs process; only finding optimal beta (c) coefficients
            echo "Running simulation set 20"
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results20/b2_T50_diff1_smally.pkl" --b_function "b2" --y_domain -10 10 --gibbs_iters 25 --t_end 50 --chunk_size 500 --start_val 0.3 --matrix_calc "chunked" --diffusion 1 --global_gig_p 0 --run_gibbs False
            python -m fredholm.fredholm_simulation --results_filepath "fredholm/fredholm_results/results20/b_gamma1_T50_diff1_smally.pkl" --b_function "b_gamma1" --y_domain -10 10 --gibbs_iters 25 --t_end 50 --chunk_size 500 --start_val 0.3 --matrix_calc "chunked" --diffusion 1 --global_gig_p 0 --run_gibbs False
            ;;
        *)
            echo "Warning: No simulations are set up for number $number. Please use a number from 0 to 15."
            ;;
    esac
done